import type { Metadata } from 'next';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { StyledRoot } from './StyledRoot';
import FooterBar from './components/Footerbar'

export const metadata: Metadata = {
  title: 'Gastos',
  description: 'Generated by create next app',
  manifest: "/manifest.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <StyledRoot>{children}</StyledRoot>
          <FooterBar />
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
